
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Coupon_System
{

using System;
    using System.Collections.Generic;
    
public partial class Buisness
{

    public Buisness()
    {

        this.CatalogCoupons = new HashSet<CatalogCoupon>();

    }


    public string buisName { get; set; }

    public string buisAddress { get; set; }

    public string buisCity { get; set; }

    public string BuisDescription { get; set; }



    public virtual Location Location { get; set; }

    public virtual Users_BuisnessOwner Users_BuisnessOwner { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<CatalogCoupon> CatalogCoupons { get; set; }

}

}
