//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogCoupons_SocialNetworkCoupon
    {
        public string origionWebsite { get; set; }
        public string Customer_userName { get; set; }
        public string Customer_userName1 { get; set; }
        public int catalogID { get; set; }
    
        public virtual CatalogCoupon CatalogCoupon { get; set; }
        public virtual Users_Customer Users_Customer { get; set; }
    }
}
