//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogCoupon
    {
        public CatalogCoupon()
        {
            this.OrderedCoupons = new HashSet<OrderedCoupon>();
        }
    
        public int catalogID { get; set; }
        public string CouponName { get; set; }
        public Nullable<double> originalPrice { get; set; }
        public Nullable<double> priceAfterDiscount { get; set; }
        public Nullable<System.DateTime> deadLineForUse { get; set; }
        public Nullable<double> averageRank { get; set; }
        public Nullable<double> Location_latitude { get; set; }
        public Nullable<double> Location_longitude { get; set; }
        public string description { get; set; }
        public string SystemAdministrator_userName { get; set; }
        public string Buisness_name { get; set; }
        public string Category_name { get; set; }
    
        public virtual Buisness Buisness { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderedCoupon> OrderedCoupons { get; set; }
        public virtual Users_SystemAdministrator Users_SystemAdministrator { get; set; }
        public virtual Location Location { get; set; }
        public virtual CatalogCoupons_SocialNetworkCoupon CatalogCoupons_SocialNetworkCoupon { get; set; }
    }
}
