
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Coupon_System
{

using System;
    using System.Collections.Generic;
    
public partial class Users_BuisnessOwner
{

    public Users_BuisnessOwner()
    {

        this.Buisnesses = new HashSet<Buisness>();

    }


    public string userName { get; set; }



    public virtual User User { get; set; }

    public virtual ICollection<Buisness> Buisnesses { get; set; }

}

}
